name: API CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-formating-test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: |
          cd api
          npm install

      - name: Checking formating code style
        run: |
          cd api
          npm run format:check

      - name: Build API
        run: |
          cd api
          npm run build
