name: API CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - 'api/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'api/**'

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --cwd ./api install

      - name: Build API
        run: yarn --cwd ./api build
