name: Docs CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  check-lint-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: |
          cd docs
          npm install

      - name: Checking eslint
        run: |
          cd docs
          npm run lint

      - name: Build React app
        run: |
          cd docs
          npm run build
